/* This program takes input from text file generated by python and send signal to NI card */
#include <stdio.h>
#include <NIDAQmx.h>
#include<stdlib.h>

int32 CVICALLBACK DoneCallback(TaskHandle taskHandle, int32 status, void *callbackData);
#define DAQmxErrChk(functionCall) if ( DAQmxFailed( error=(functionCall)) ) goto Error ; else
/***************************  MAIN PROGRAM **********************************************/
int main( void)
{
    int         error = 0 ;
    TaskHandle  taskHandle = 0 ;
    long long i,n ;
    // fake signal to blank address                                   17th bit-->[0,0,0,0,0,0,0,0]<-- 24th bit
    uInt32 blank_0 = 50331648 ; // {0,0,0,0,0,0,0,0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0} with strobe 1
    uInt32 blank_1 = 33554432 ; // {0,0,0,0,0,0,0,0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0} with strobe 0

    char errBuff[2048] = {'\0'};
                                                                                        //->26<- pin is high
    uInt8 reset[32] = {0,0,0,0,0,0,0,0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0} ;

    /**************************BLOCK TO GENERATE data[n] array**************************************/
    // Open the file for reading which has signal information in the form 32bit int as first column and signal number second column
    FILE* file = fopen("text_file.txt", "r");
    
    if (file == NULL) { printf("Failed to open the file.\n"); return 1; }
    /*-----block to calculate number of rows in the file.------------*/
    int rows = 0;
    int c;

    while ((c = fgetc(file)) != EOF) // 
    {
        if (c == '\n')
        { 
            rows++;
        }
    }
    rewind(file);  // Reset the file pointer to the beginning of the file.
    /*-----END of block to calculate number of rows in the file.------------*/

    // Read the 32 bit signal and  signal number from the file
    long long** signal_info = (long long**)malloc(rows * sizeof(long long*));
    for (i = 0; i < rows; i++)
    {
        signal_info[i] = (long long*)malloc(2 * sizeof(long long));
        fscanf(file, "%lld \t %lld", &signal_info[i][0], &signal_info[i][1]);
    }
    fclose(file);

    n = signal_info[rows-1][1] ;

    printf("Total a number of samples %lld : \n",n);

    if (n%2 == 0) { n = n+1 ; } // n should be odd which will make number of elements in data[n] array even.
    
    printf("Type a number of samples : \n");
    printf("Experiment Run Time in microseconds %lld \n",2*(n-1));
    printf("Experiment Run Time in milliseconds %lld \n",2*(n-1)/1000);
    printf("Experiment Run Time in seconds %lld \n",2*(n-1)/1000000);
    printf("Experiment Run Time in minutes %lld \n",2*(n-1)/60000000);
    
    //uInt32 data[n]; // initisalise in usual way

   // memset(data, 0, sizeof(data));  // Initialize data array to zero
    
    uInt32 *data;
    data = (uInt32*)malloc(n * sizeof(uInt32));

    // first filling data for blank addresses
    for(i=0;i<n;i=i+2)
    {
        data[i] = blank_0 ;
        data[i+1] = blank_1 ;
    }

    // Entering signal into data array
    for(i=0;i<rows;i++)
    {
        data[signal_info[i][1]] = signal_info[i][0]; // writing information on top of blank array data[n]
    }
    
     // Free dynamically allocated memory
    for (i = 0; i < rows; i++) {
        free(signal_info[i]);
    }
    free(signal_info);
   /************************** data[n] array is generated **************************************/    
   
   /************************** BLock to program NI card   **************************************/ 
    /*Resetting the buffer card*/
    DAQmxErrChk(DAQmxCreateTask("",&taskHandle));
    DAQmxErrChk(DAQmxCreateDOChan(taskHandle,"Dev2/port0:3","",DAQmx_Val_ChanForAllLines)) ; // we can give name to each channel(char) in third "".
    DAQmxErrChk(DAQmxStartTask(taskHandle));
    DAQmxErrChk(DAQmxWriteDigitalLines(taskHandle,1,1,0.0,DAQmx_Val_GroupByChannel,reset,NULL,NULL));
    DAQmxErrChk(DAQmxStopTask(taskHandle));
    DAQmxErrChk(DAQmxClearTask(taskHandle));
    
     /* DAQmx configure code */
    DAQmxErrChk(DAQmxCreateTask("",&taskHandle));
    DAQmxErrChk(DAQmxCreateDOChan(taskHandle,"Dev2/port0:3","",DAQmx_Val_ChanForAllLines)) ;
    DAQmxErrChk(DAQmxCfgSampClkTiming(taskHandle, NULL, 500000, DAQmx_Val_Rising, DAQmx_Val_FiniteSamps, n)); 
    DAQmxErrChk(DAQmxCfgOutputBuffer(taskHandle,n));
    DAQmxErrChk(DAQmxRegisterDoneEvent(taskHandle,0,DoneCallback,NULL));
    DAQmxErrChk(DAQmxWriteDigitalU32(taskHandle,n,0,-1,DAQmx_Val_GroupByChannel,data,NULL,NULL));
    
    /* DAQmx Start Code*/
    DAQmxErrChk(DAQmxStartTask(taskHandle));
    //printf("NI card id generating digital output. Press Enter to interrupt\n");
    //getchar();
    DAQmxErrChk(DAQmxWaitUntilTaskDone(taskHandle,-1));
	printf("Time sequence is completed.\n");
    getchar();
    Error:
    if (DAQmxFailed(error))
        DAQmxGetExtendedErrorInfo(errBuff,2048);
    if(taskHandle!=0)
        {
            /*DAQmx stop code*/
            DAQmxStopTask(taskHandle);
            DAQmxClearTask(taskHandle);
        }
        if (DAQmxFailed(error))
            printf("DAQmx Error: %s\n",errBuff);
        printf("End of program, press enter key to quit\n");
        getchar();
        return 0;
  /************************** END OF PROGRAM **************************************/
}

int32 CVICALLBACK DoneCallback(TaskHandle taskHandle, int32 status, void *callbackData)
{
    int32 error = 0;
    char errBuff[2048] = {'\0'} ;
    // Check to see if an error stopped the task.
    DAQmxErrChk(status);
Error:
    if (DAQmxFailed(error)){
        DAQmxGetExtendedErrorInfo(errBuff,2048);
        DAQmxClearTask(taskHandle);
        printf("DAQmx Error: %s\n",errBuff);
    }
    return 0;
}


